package hu.kszi2.nought.io;

import hu.kszi2.nought.core.Todo;
import hu.kszi2.nought.core.TodoStore;
import org.jetbrains.annotations.Contract;
import org.jetbrains.annotations.NotNull;

import javax.xml.stream.*;
import java.io.Writer;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Implements the {@link TodoExporter} interface with exporting to an XML file.
 * The XML is valid to the schema found in the resources directory of the project.
 */
public class TodoXMLExporter implements TodoExporter {
    /**
     * The XML namespace used by the nought XML files.
     * This is set as the default namespace in the XML file generated by the exporter.
     */
    public static final String NOUGHT_NAMESPACE = "https://kszi2.hu/~bodand/nought.xsd";

    /**
     * Constructs an exporter object with setting the store to export to the given one.
     *
     * @param store The store to export
     */
    public TodoXMLExporter(TodoStore store) {
        this.store = store;
    }

    @Override
    public void export(Writer writer) throws XMLStreamException {
        var factory = XMLOutputFactory.newFactory();
        stream = factory.createXMLStreamWriter(writer);

        stream.setDefaultNamespace(NOUGHT_NAMESPACE);
        stream.writeStartDocument();
        stream.writeStartElement(NOUGHT_NAMESPACE, "nought");
        stream.writeDefaultNamespace(NOUGHT_NAMESPACE);
        stream.writeStartElement(NOUGHT_NAMESPACE, "todos");

        var it = store.iterator();
        while (it.hasNext()) {
            addTodoOutput(it.next());
        }

        stream.writeEndDocument(); //</todos></nought>
        stream.close();

        stream = null;
        written.clear();
    }

    /**
     * <p>
     * Writes a given todo to the output, if its children have all been written to
     * it already.
     * </p>
     * <p>
     * If the todo is written to the output, its parent is written as well, recursively using this
     * function.
     * </p>
     *
     * @param todo The todo to write
     * @throws XMLStreamException XML export error occurred
     */
    private void addTodoOutput(@NotNull Todo todo) throws XMLStreamException {
        var children = todo.getChildren();
        if (wroteAllChildren(children)) {
            writeTodo(todo);
            var parent = todo.getParent();
            if (parent != null) {
                addTodoOutput(parent);
            }
        }
    }

    /**
     * Formats a GUID to the appropriate format for writing it out as an XML tag value.
     * Since GUIDs may begin with a number, they need to be formatted to allow them to be used in an
     * attribute whose type is {@code xsd:ID}, where {@code xsd} is the XML Schema Definition
     * namespace.
     *
     * @param id The GUID to format
     * @return The formatted string output
     */
    @Contract(pure = true)
    private @NotNull String formatGuid(@NotNull UUID id) {
        return "_" + id;
    }

    /**
     * Checks is a list of todos with the given ids have all been written to the output already.
     * It is used to check if a given todo's children have already been written before writing
     * that given todo out as well.
     *
     * @param cids The list of ids to check
     * @return Whether they have all been written to output
     */
    private boolean wroteAllChildren(List<UUID> cids) {
        return written.containsAll(cids);
    }

    /**
     * Checks if a todo has been written to the output.
     * If yes, the function is nop.
     * Otherwise, writes the appropriate tags representing a todo in the XML Schema, including
     * all sub-tags required.
     *
     * @param todo The todo to write out
     * @throws XMLStreamException XML export error occurred
     */
    private void writeTodo(@NotNull Todo todo) throws XMLStreamException {
        if (written.contains(todo.getId())) return;

        written.add(todo.getId());
        stream.writeStartElement(NOUGHT_NAMESPACE, "todo");
        stream.writeAttribute(NOUGHT_NAMESPACE, "id", formatGuid(todo.getId()));
        // 1. name
        writeTodoField("name", todo.getName());
        // 2. desc
        writeTodoField("desc", todo.getDescription());
        // 3. completed?
        if (todo.isCompleted()) {
            stream.writeEmptyElement(NOUGHT_NAMESPACE, "completed");
        }
        // 4. depends-on?
        writeChildren(todo);
        // 5. due?
        writeDue(todo);

        stream.writeEndElement();
    }

    /**
     * Writes a given todo's children as todo reference tags to the output.
     *
     * @param todo The todo whose children are to be written
     * @throws XMLStreamException XML export error occurred
     */
    private void writeChildren(@NotNull Todo todo) throws XMLStreamException {
        var children = todo.getChildren();
        if (children.isEmpty()) return;

        stream.writeStartElement(NOUGHT_NAMESPACE, "depends-on");
        for (var child : children) {
            writeTodoRef(child);
        }
        stream.writeEndElement();
    }

    /**
     * Writes a todo reference tag to reference the given id.
     *
     * @param id The id to write a reference to
     * @throws XMLStreamException XML export error occurred
     */
    private void writeTodoRef(UUID id) throws XMLStreamException {
        stream.writeEmptyElement(NOUGHT_NAMESPACE, "todo");
        stream.writeAttribute("ref", formatGuid(id));
    }

    /**
     * Mostly generic text-based field output function.
     * Writes a given tag (field), with the provided string data as its value.
     *
     * @param field The field of the todo to write
     * @param data  The data to output
     * @throws XMLStreamException XML export error occurred
     */
    private void writeTodoField(String field, String data) throws XMLStreamException {
        if (data == null) return;
        stream.writeStartElement(NOUGHT_NAMESPACE, field);
        stream.writeCharacters(data);
        stream.writeEndElement();
    }

    /**
     * Writes the "due-data" of a given todo object.
     * If the todo has any associated due date/due time fields, the enclosing XML tag is written
     * with the actually non-null fields inside.
     *
     * @param todo The todo whose due fields are to be written
     * @throws XMLStreamException XML export error occurred
     */
    private void writeDue(@NotNull Todo todo) throws XMLStreamException {
        var date = todo.getDueDate();
        var time = todo.getDueTime();
        if (date == null) return;

        stream.writeStartElement(NOUGHT_NAMESPACE, "due");
        // 1. date
        writeTodoField("date", formatDate(date));
        // 2. time?
        writeTodoField("time", formatTime(time));

        stream.writeEndElement();
    }

    /**
     * Formats a time to the appropriate ISO style as a string.
     * This can be written out into the XML file.
     * The format used is {@code HH:mm:ss}.
     *
     * @param time The time object to stringify.
     * @return The formatted time as a string
     */
    private String formatTime(LocalTime time) {
        if (time == null) return null;
        var format = DateTimeFormatter.ofPattern("HH:mm:ss");
        return format.format(time);
    }

    /**
     * Formats a date to the appropriate ISO (long) style as a string.
     * This can be written out into the XML file.
     * The format used is {@code yyyy-MM-dd}.
     *
     * @param date The date object to stringify.
     * @return The formatted date as a string
     */
    private String formatDate(Date date) {
        if (date == null) return null;
        var format = new SimpleDateFormat("yyyy-MM-dd");
        return format.format(date);
    }

    private XMLStreamWriter stream;
    private final TodoStore store;
    private final Set<UUID> written = new HashSet<>();
}
