= Nought
Bodor András - YZBQWV
3, {docdate}: Programozás alapjai 3 házifeladat
:title-separator: ,
:version-label: Verzió
:email: bodand@kszi2.hu
:appendix-caption: Függelék
:example-caption: Példa
:figure-caption: Ábra
:listing-caption: Listázás
:table-caption: Táblázat
:note-caption: Megjegyzés
:lang: hu
:doctype: book
:media: screen
:chapter-signifier:
:sectnums:
:toc:
:toc-title: Tartalomjegyzék
:source-highlighter: rouge
:mathematical-format: svg
:stem: latexmath

== Specifikáció

=== Feladatleírás

Nought egy teendőket tároló alkalmazás.
A felhasználó fel tud venni teendőket, amikhez egy rövid nevet, és egy hosszabb leírást rendelhet.
Ezeket a felhasználó kedve szerint lehetséges elkészültnek jelölni.
Egy teendőnek emellett lehet határideje dátummal és opcionálisan időponttal.

A teendők hierarchiába állíthatóak, minden elemnek tetszőleges számú aleleme lehetséges.
Egy elem, ha vannak alelemei csak akkor állítható elkészültnek, ha minden aleleme már az, és egy elem csak akkor állítható vissza nem elkészülté, ha a szülő eleme nincs elkészülve.

Minden alteendő nélkül teendőt egyszerűen lehetséges törölni a rendszerből, de lehetséges egy egész teendő hierarchia kitörlése külön menüponton keresztül, a teendővel és minden alteendőjével.

Az aktuálisan felvett teendők egy fa struktúrában jelennek meg, ahol ki lehet őket választani.
A jelenleg kiválasztott teendő adatai jelennek meg a képernyő többi részén, ahol lehet őket módosítani.
A bevitt adatok érvényességét a rendszer ellenőrzi és az érvényteleneket visszautasítja.

=== Use-casek

. A felhasználó fel tud venni új teendőt a teendő-lista legfelső szintjére.
. A felhasználó kijelölhet egy teendőt a teendő-listában.
. A kijelölt teendőt lehetséges átnevezni, ennek a névnek nem szükséges különbözőnek lennie.
. Ha a kijelölt teendő nevét üresre állítaná a felhasználó, akkor azt visszautasítja a program.
. A kijelölt teendőnek a többsoros leírását lehetséges módosítani.
. A kijelölt teendőnek lehetséges határidőt beállítani.
. A kijelölt teendő határideje egy dátumként és egy időpontként adható meg.
. Egy teendő határidejéhez időpont csak akkor adható, ha dátum már hozzá lett rendelve.
. A megadott dátumot lokális dátumként értelmezi a rendszer, és ha nem értelmes dátum került megadásra, akkor visszautasítja.
. Ha érvénytelen időpont kerül megadásra, akkor azt visszautasítja a rendszer.
. A kijelölt teendő alá felvehető alteendő.
. Egy teendő beállítható elkészítetté, ha már minden alteendője (ha vannak) készre lett állítva.
. Egy teendő törölhető, ha nincsenek neki alteendői.
. A file menüpontban lehetséges elmenteni a jelenlegi todo állapotokat.
. A file menüpontban a felhasználó képes más todo fájlokat megnyitni.
. A file menüpontban tudja a felhasználó bezárni az ablakot.
. A felhasználó a todo menüpontban tud új gyökér teendőt felvenni.
. A todo menüpont alatt lehetséges új alteendőket felvenni a jelenleg kijelölt menüpont alá.
. A todo menüpontban lehetséges kitörölni a jelenleg kijelölt teendőt, ha nincsenek alteendői.
. A todo menüpont alatt tudja a felhasználó kitörölni a jelenleg kijelölt teendőt, és az összes hozzá tartozó alteendőt.
. Ha nincs egy teendő se kijelölve, akkor minden adatbeviteli mező inaktív.

=== Megoldás vázlat

==== Képernyő vázlat

A kész grafikus felhasználói felületet a program a Java Swing grafikus rendszerén fogja megvalósítani.
Az alábbi diagram mutatja be, hogy nagyságrendileg, hogy fog kinézni az elkészült program.

[plantuml,format=svg]
----
@startsalt
{#
{* File | Todo } | *
{
Name | "SubSubTodo 2      "
Description | {SI
Complex description
.
.
Multiline :)
.
"               "
}
Due | {
    Date | "              "
    Time | "              "
}
.
[] Completed
.
[ Add subtodo ] | [ Remove ]
}|{{T
+ Todo1
++ SubTodo1
+++ SubSubTudo1
+++ <back:lightblue>SubSubTudo2</back>
++ SubTodo2
+ Todo2
+ Todo3
+ Todo4
++ SubTodo3
+++ SubSubTodo3
++++ SubSubSubTodo1
+++++ SubSubSubSubTodo1
}
.
.
[ New ]
}
}
@endsalt
----

==== Fájlformátum

A nought file formátum egy XML fájl, amiben tárolásra kerülnek a különböző todo elemek és a hozzájuk tartozó adatok.
A fájlhoz a következő XML Schema tartalmazza az XML formátumát.

.nought.xsd
[source,xml]
----
include::src/main/resources/nought.xsd[]
----

NOTE: A sémát jelző URL még nem mutat érvényes/létező adatra.

A fenti XML Schema nem ellenőriz minden szemantikai szükségletet, egyedül a referenciák valós todo elemekre való referálását vizsgálja.
Explicite kényszereket értékekre nem tartalmaz a típusokon kívül.

Minden elemnek egy fájlon belül egyedi azonosítóval kell rendelkeznie, amit a program GUID-k használatával fog megvalósítani.
